// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using church_database;

#nullable disable

namespace church_database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230218042044_AddedProjectsEntity")]
    partial class AddedProjectsEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("church_models.Entities.ApplicantCommunity", b =>
                {
                    b.Property<int>("ApplicantCommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantCommunityId"), 1L, 1);

                    b.Property<string>("ApplicantCommunityDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantCommunityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ApplicantCommunityId");

                    b.ToTable("ApplicantCommunity");
                });

            modelBuilder.Entity("church_models.Entities.ApplyingEntity", b =>
                {
                    b.Property<int>("ApplyingEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplyingEntityId"), 1L, 1);

                    b.Property<string>("ApplyingEntityDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplyingEntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ApplyingEntityId");

                    b.ToTable("ApplyingEntity");
                });

            modelBuilder.Entity("church_models.Entities.CompletionStatus", b =>
                {
                    b.Property<int>("CompletionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletionStatusId"), 1L, 1);

                    b.Property<string>("CompletionStatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CompletionStatusId");

                    b.ToTable("CompletionStatus");
                });

            modelBuilder.Entity("church_models.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<int?>("AmountToBeAppliedForAgencies")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantCommunityId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicantEmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplyingEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionStatusId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DesiredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedEndOfProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalContribution")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalProjectCost")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ApplicantCommunityId");

                    b.HasIndex("ApplyingEntityId");

                    b.HasIndex("CompletionStatusId");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("church_models.Entities.ProjectStatus", b =>
                {
                    b.Property<int>("ProjectStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectStatusId"), 1L, 1);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectStatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectStatusId");

                    b.ToTable("ProjectStatus");
                });

            modelBuilder.Entity("church_models.Entities.ProjectType", b =>
                {
                    b.Property<int>("ProjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTypeId"), 1L, 1);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectTypeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTypeId");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("church_models.Entities.Project", b =>
                {
                    b.HasOne("church_models.Entities.ApplicantCommunity", "ApplicantCommunity")
                        .WithMany()
                        .HasForeignKey("ApplicantCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("church_models.Entities.ApplyingEntity", "ApplyingEntity")
                        .WithMany()
                        .HasForeignKey("ApplyingEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("church_models.Entities.CompletionStatus", "CompletionStatus")
                        .WithMany()
                        .HasForeignKey("CompletionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("church_models.Entities.ProjectStatus", "ProjectStatus")
                        .WithMany()
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("church_models.Entities.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantCommunity");

                    b.Navigation("ApplyingEntity");

                    b.Navigation("CompletionStatus");

                    b.Navigation("ProjectStatus");

                    b.Navigation("ProjectType");
                });
#pragma warning restore 612, 618
        }
    }
}
